### ISSUE TITLE
Inverted dowload links

### ISSUE THREAD

**Issue by dkgs** [conan-io/website#1]
Hi,

Just to say that the download link to win32x86_64 points to https://github.com/conan-io/conan/releases/download/1.0.0/conan-win-32_1_0_0.exe and the link for win x86 points to https://github.com/conan-io/conan/releases/download/1.0.0/conan-win-64_1_0_0.exe.

**Comment by memsharded** [comment]
Thanks for noticing! Fixing it right now.

**Comment by memsharded** [comment]
Fixed now :)
