### ISSUE TITLE
Make space for more logos

### ISSUE THREAD

**Issue by memsharded** [conan-io/website#133]
We are going to add more company logos. It is necessary to have a place to add them easily.

Alternatives:

- Have some animation that changes them, randomly, fade-in-out, or something like that.
- Make the grid bigger, to include more of them
- Other kind of animation?

cc /@nadavc-jfrog

**Comment by uilianries** [comment]
I think random logo + fade-in-out should work. A bigger grid will look polluted I think.

![Screenshot_2020-08-03 C C++ Open Source Package Manager](https://user-images.githubusercontent.com/4870173/89178332-c31a9800-d563-11ea-8f20-b5864108c0af.png)
