### ISSUE TITLE
Recipe syntax highlighting is broken

### ISSUE THREAD

**Issue by mathbunnyru** [conan-io/website#195]
For example, if I open this page https://conan.io/center/valijson?tab=recipe, python syntax highlighting is not working.

It worked well before the latest update.

**Comment by mathbunnyru** [comment]
Sorry, previous issue was in the wrong place: https://github.com/conan-io/conan-center-index/issues/3127

**Comment by Croydon** [comment]
It is the other way around. CCI is the right place, hence the issue template and issue label https://github.com/conan-io/conan-center-index/labels/conan.io%2Fcenter

**Comment by mathbunnyru** [comment]
Oh, wow, sorry :)
