### ISSUE TITLE
Checkbox didn't show in Chrome.

### ISSUE THREAD

**Issue by memsharded** [conan-io/website#26]
Sign up for releases in the same page, the checkbox for 'I have read and agree to the Privacy Policy' didn't show up on **Chrome in Windows**.  It showed up fine in Microsoft Edge.

![capture](https://user-images.githubusercontent.com/15367152/47704609-7edac500-dc24-11e8-9b93-de185794cdf9.PNG)

**Comment by lasote** [comment]
Specify OS and browser. It is ok in Chrome/Mac, Safari/Mac

**Comment by Croydon** [comment]
I have confirm this in Chrome 70 and Opera 56.

It is working as expected in Firefox 63 and Edge.

All tested on Win 10.

**Comment by lasote** [comment]
Closes by #27 26
