### ISSUE TITLE
[feature] conan.io/downloads.html: Docker Swarm

### ISSUE THREAD

**Issue by alejandro-colomar** [conan-io/website#267]
In the downloads website you have a tarball for deploying a jfrog server with docker compose.
You could maybe add the same for Docker Swarm to achieve high availability, so that it can be deployed in a multi-host cluster.

Aside:  I think the term you are using (Docker Compose Installer) is inexact and misleading, as it's not really installing anything in the system.

- [ x ] I've read the [CONTRIBUTING guide](https://github.com/conan-io/conan/blob/develop/.github/CONTRIBUTING.md).

**Comment by lasote** [comment]
Hi, I've moved the issue to the website repository. 
About docker swarm and Artifactory. I've found [this link](https://github.com/jfrog/artifactory-docker-examples/tree/master/swarm) about it but it is only an example. I checked the main Jfrog platform download page and there is no direct item for swarm: https://jfrog.com/download-jfrog-platform/ So for us (the conan team) is a bit of out our scope.

**Comment by prince-chrismc** [comment]
This is covered by the SaaS and helm charts for the paid version of Artifactory https://jfrog.com/infographic/jfrog-saas-vs-self-hosted/ 

Going to mark this as closed since it's out of scope for us :)
