### ISSUE TITLE
Add confirmation email to release signup

### ISSUE THREAD

**Issue by solvingj** [conan-io/website#281]
On https://conan.io homepage, when users provide their email to subscribe to new release updates, they do not currently receive any confirmation email.

**Comment by solvingj** [comment]
I have sent a message internally to the person who administers emails to ask if they can do that through the email platform.

**Comment by solvingj** [comment]
From Marketing Team:

Hey, just wanted to give you an update on this. I have not created this one yet as we are finalizing swamp up. But i will try to get this done by next week. 

Thank you

**Comment by prince-chrismc** [comment]
I just got one testing the form so this must have been done 🚀
