### ISSUE TITLE
Remove tribe banners and add navigation for tribe.html

### ISSUE THREAD

**Issue by solvingj** [conan-io/website#283]
There are currently 2 tribe banners on the conan.io homepage. We would now like to remove these. 

There is also the following page:

https://conan.io/tribe.html

The banners on the homepage are currently the only navigation mechanism which reaches this page.  So, after removing, we need to figure out how to make this page navigable using some more traditional strategy than banners.

**Comment by prince-chrismc** [comment]
There is only 1 banner, as a celebration, to the tribe who helped with 2.0

Closing this since it's not related to the current design
