### ISSUE TITLE
Remove JFrog Academy banner, add new dedicated page learn.html

### ISSUE THREAD

**Issue by solvingj** [conan-io/website#284]
The JFrog academy banner has been around long enough and it should be removed from the homepage now. 

This can be done immediately.

However, as next step, it would be good to create a new dedicated page which provides a summary with links to all the resources  available for learning:

docs
jfrog academy
examples repository
cheat sheet
youtube videos
known "getting started" blog posts

If we create such a page, we will need a way to make it navigable from the homepage, as currently there is no suitable navigation mechanism other than the banner.

**Comment by prince-chrismc** [comment]
The banner was removed and the "learn" section lives on the docs website :)
