### ISSUE TITLE
wrong link to artifactory-ce at conan.io download page

### ISSUE THREAD

**Issue by sebkraemer** [conan-io/website#286]
### Steps to reproduce (Include if Applicable)
- Visit `https://conan.io/downloads.html`
- click *Getting Started with Artifactory CE*

### Logs
Browser calls `https://docs.conan.io/en/latest/uploading_packages/artifactory_ce.html`
and gives "Page Not Found"
I think that should say `https://docs.conan.io/en/latest/uploading_packages/artifactory/artifactory_ce.html` (additional subdirectory added).

**Comment by StellaSmith** [comment]
This also happens in https://conan.io/ after scrolling down and clicking "Learn More >" in the "ARTIFACTORY CE" box.
