### ISSUE TITLE
Adding new package link at conan center webpage is broken 

### ISSUE THREAD

**Issue by vissarion** [conan-io/website#325]
In https://conan.io/center/ the link for new packages 

[Click here to learn more about Adding New Packages to ConanCenter](https://github.com/conan-io/conan-center-index/blob/master/docs/how_to_add_packages.md)

is broken. 

Maybe this  could be replaced by 

[Click here to learn more about Adding New Packages to ConanCenter](https://github.com/conan-io/conan-center-index/tree/master/docs/adding_packages)

**Comment by prince-chrismc** [comment]
This is generically point to https://github.com/conan-io/conan-center-index/tree/master/docs#readme which has the `adding_packages/` section :)
