### ISSUE TITLE
Page downloads.html suggests using AUR helper that is no longer available

### ISSUE THREAD

**Issue by sergey-bon** [conan-io/website#33]
## Summary

https://github.com/conan-io/website/blob/f9e42712bc92f2e46724509a10827cd4b433e493/downloads.html#L139

[pacaur](https://github.com/rmarquis/pacaur) is no longer maintained and the package is not available in Arch repositories. As for this date, the most popular AUR helper is [yay](https://github.com/Jguer/yay), which is itself only available from AUR.

## Possible solutions

* Replace `pacaur` with `yay`. Installing a package from AUR requires installing its dependencies and doing that manually is tedious, so `yay` or some other wrapper is likely to be used anyways.
* Replace `$ pacaur -S conan` with a link to Arch Wiki article on [installing packages from the AUR](https://wiki.archlinux.org/index.php/AUR#Installing_packages) and let users figure this out themselves.

**Comment by memsharded** [comment]
Thanks @sergey-bon for the feedback.

The pacaur package is maintained by @tivek, maybe they can give feedback about this issue.
