### ISSUE TITLE
FAQ: bad PR link

### ISSUE THREAD

**Issue by GitMensch** [conan-io/website#343]
Current link in https://conan.io/faq.html points to https://github.com/conan-io/conan-io.github.io/pulls, but should point to https://github.com/conan-io/conan/pulls - as I don't see where this is maintained, here's an issue instead of a PR to fix that.

**Comment by RubenRBS** [comment]
Fixed! @prince-chrismc had fixed it a few days ago but we did not get around releasing the changes until you yesterday, thanks for the heads-up!
