### ISSUE TITLE
Carousel doesn't work when loading after update

### ISSUE THREAD

**Issue by memsharded** [conan-io/website#82]
![Untitled](https://user-images.githubusercontent.com/15367152/72257182-477aed00-360b-11ea-89d4-34ed154626e7.png)

After the web is updated, loading it shows a broken carousel. When a refresh is done, then it works.

Windows, Chrome browser. Verified by other Conan users too.

**Comment by prince-chrismc** [comment]
This must have been fixed in a previous iteration 
![image](https://user-images.githubusercontent.com/16867443/223575408-cdd5e0bc-0b2b-49a5-8111-61f71e5e5196.png)
