### ISSUE TITLE
Missing API permissions to create slack invite

### ISSUE THREAD

**Issue by joelpurra** [conan-io/website#96]
In the top menu bar there is a Slack icon. Clicking it leads to a separate server/service for joining (automatically creating a Slack invitation) the CPPLang Slack.

- https://cpplang.now.sh/

Unfortunately, the server seems misconfigured, as the button changes from "get my invite" to `no_perms` when submitting. Attached a screenshot (email address removed) which also shows that the captcha was properly solved.

I would guess that regenerating/configuring a Slack API key for the `slackin` deployment would fix the issue.

- https://github.com/rauchg/slackin

![Screenshot from 2020-04-10 10-19-01](https://user-images.githubusercontent.com/1398544/78975650-d1582a80-7b14-11ea-9a50-872192ec03e0.png)

**Comment by memsharded** [comment]
Hi @joelpurra 

This slack is not managed by us, it is managed by the Cpp Foundation. They have commented that this invite server is down for maintenance, and are commenting about cpplang-inviter.cppalliance.org being the new one. Can you try this new one?

Still personal invites can be sent by members. If the above still not work, please send us your email to info@conan.io, and we will invite you.

**Comment by joelpurra** [comment]
@memsharded: yeah, wasn't sure it was managed by conan, based on the name. I can confirm that the new invitation service is working, so guess the link(s) can be updated. Thanks!

**Comment by memsharded** [comment]
Updated in: https://github.com/conan-io/conan
Docs: https://github.com/conan-io/docs/pull/1664
Changed in conan.io too

Thanks very much for reporting this!
